#!/usr/bin/env bash
# Date: 2016-08-23
# Function: Show Screensaver in Ubuntu Desktop 14.04 LTS
# Prerequisite: 
#	           1. cmatrix
#	           2. cpulimit
#	           3. xdotool
# Maintainer: Yuntao Ren <rytubuntulinux@gmail.com>

pid=`pidof cpulimit`
color_array=(green red blue white yellow cyan magenta black)
color_array_len=${#color_array[@]}
index=`echo "$RANDOM % ${color_array_len}" | bc`

limit_cpu=5
secret_key="Geek"

# Used by `read`
timeout=5
prompt='Please Input the Secret Key: '


# Get the path of `cmatrix`
limit_program_path=`which cmatrix`

# The program `cpulimit` is not running
if [ "${pid}" == "" ]
then
	echo "Run cpulimit..."
	cpulimit -l ${limit_cpu} -P ${limit_program_path} &
	echo "cpulimit is running..."

	# Show Screensaver
	cmatrix -s -b -C ${color_array[${index}]}

	# Input the Secret Key
	read -s -t ${timeout} -p ${prompt} var

	# Check if the `var` equal to `secret_key`
	if [ "${var}" == "${secret_key}" ]
	then
		exit 0
	else
		# Lock the screen
		xdotool key Ctrl+Alt+l
	fi
# The program `cpulimit` is already running
else
	echo "cpulimit already running..."

	# Show Screensaver
	cmatrix -s -b -C ${color_array[${index}]}

	# Input the Secret Key
	read -s -t ${timeout} -p "${prompt}" var

	# Check if the `var` equal to `secret_key`
	if [ "${var}" == "${secret_key}" ]
	then
		exit 0
	else
		# Lock the screen
		xdotool key Ctrl+Alt+l
	fi
fi

exit 0
