#!/usr/bin/env bash
# Date: 2016-08-23
# Function: Show Screensaver in Ubuntu Desktop 14.04 LTS
# Prerequisite: 
#	           1. cmatrix
#	           2. cpulimit
#	           3. xdotool
# Maintainer: Yuntao Ren <rytubuntulinux@gmail.com>

# Ignore Ctrl-C and Ctrl-Z
trap '' SIGINT SIGTSTP SIGKILL

# Entered full-screen display in the terminal
lines1=`tput lines` &&  xdotool key F11 && sleep 1 && lines2=`tput lines`
if [ $lines1 -gt $lines2 ]
then
	xdotool key F11
fi

# The path of screensaver configure file
config_file="/etc/screensaver.conf"

# When you quit from the screensaver, you should input the 
# correct value of secret_key in ${timeout} seconds;
# otherwise, the desktop will be locked.
#
# Read secret key and timeout from the file 'screensaver_config'
counter=1
while read -r var
do
	if [ "$counter" == "1" ]
	then
		secret_key=$var
	else
		timeout=$var
	fi

	let '++counter'

done < "$config_file"


# Get pid of `cpulimit`
pid=`pidof cpulimit`

# limit cpu usage, percentage of CPU allowed(Useed by `cpulimit`)
limit_cpu=5

# Store the color of screensaver in array `color_array`
# and get the length of array `color_array`
color_array=(green red blue white yellow cyan magenta black)
color_array_len=${#color_array[@]}

# Generate Random Number in Range [1,${color_array_len})
index=`echo "$RANDOM % ${color_array_len}" | bc`

# Used by `read`
prompt='Please Input the Secret Key: '

# When you quit from the screensaver, you should input the 
# correct value of secret_key(in this case, it's "Geek")
# in ${timeout} seconds(in this case, it's 5 seconds), 
# otherwise, the desktop will be locked.
#secret_key="Geek"

# Show Help
function show_help
{
	echo ""
	echo -e "\e[1m*************************** Help ********************************\e[0m"
	echo ""
	echo -e "\e[1mNAME\e[0m"
	echo -e "    screensaver - Show Screensaver in Ubuntu Desktop 14.04 LTS"
	echo ""
	echo -e "\e[1mSYNOPSIS\e[0m"
	echo -e "    \e[1mscreensaver\e[0m [\e[1m-h\e[0m] [\e[1m-c\e[0m] [\e[1m-s\e[0m] [\e[1m-t\e[0m \e[3m\e[4mtimeout\e[0m]"
	echo ""
	echo -e "\e[1mOPTIONS\e[0m"
	echo ""
	echo -e "  \e[1m-c\e[0m"
	echo "     Change the secret key"
	echo ""
	echo -e "  \e[1m-h\e[0m"
	echo "     Show this help and exit"
	echo ""
	echo -e "  \e[1m-s\e[0m"
	echo "     Show the secret key and timeout, then exit"
	echo ""
	echo -e "  \e[1m-t\e[0m \e[3m\e[4mtimeout\e[0m"
	echo -e "     When you quit from screensaver, you must input the correct"
	echo -e "     Secret Key in \e[3m\e[4mtimeout\e[0m second(s); otherwise, the desktop"
	echo -e "     will be locked"
	echo ""
	echo -e "\e[1m*****************************************************************\e[0m"
	echo ""
}


# Parsing arguments with `getopts`
while getopts ":chst:" opt
do
	if [ "$?" != "0" ]
	then
		echo "getopts error...\n"
		exit 1
	fi

	case $opt in
		# Change the secret key
		c)
			echo -e "\e[1m\e[96mChange the Secret Key...\e[0m"
			echo -ne "\e[1m\e[34mInput the password: \e[0m"
			read -rs passwd
			echo "${passwd}" | sudo -kS ls &> /dev/null

			# The password user input is correct 
			if [ "$?" == "0" ]
			then
				echo ""
				# Input the new Secret Key
				echo -ne "\e[1m\e[34mInput the new secret key: \e[0m"
				read -sr new_passwd
				echo ""
				echo -ne "\e[1m\e[34mRepeat the new secret key: \e[0m"
				read -sr repeat_new_passwd
				echo ""

				# Check if the two secret keys are equal
				if [ "$new_passwd" == "$repeat_new_passwd" ]
				then
					echo "${new_passwd}" > "$config_file"
					echo "${timeout}" >> "$config_file"
					echo -e "\e[1m\e[95mThe secret key has changed successfully!\e[0m"
					exit 0
				else
					echo -e "Error: $0: \e[1m\e[31mThe two secret keys don't match!\e[0m"
					exit 0
				fi
			# The password user input is incorrect
			else
				echo -e "\nError: $0: \e[1m\e[31mIncorrect password!\e[0m"
				exit 1
			fi

			;;
		# Show help
		h)
			clear
			show_help
			exit 0
			;;
		# Show secret key
		s)
			echo -e "\e[1m\e[96mShow the Secret Key...\e[0m"
			echo -ne "\e[1m\e[34mInput the password: \e[0m"
			read -s passwd
			echo ${passwd} | sudo -Sk ls &> /dev/null

			# The password user input is correct
			if [ "$?" == "0" ]
			then
				echo -e "\n\n\e[1m\e[35mSecret Key:\e[0m \e[1m$secret_key\e[0m"
				echo -e "\e[1m\e[35mTimeout:\e[0m \e[1m$timeout\e[0m\n"
				exit 0
			# The password user input is incorrect
			else
				echo -e "\nError: $0: \e[1m\e[31mIncorrect password!\e[0m"
				exit 1
			fi
			;;
		# Set timeout
		t)
			echo -e "\e[1m\e[96mSet the timeout...\e[0m"
			new_timeout=$OPTARG

			echo -ne "\e[1m\e[34mInput the password:\e[0m"
			read -s passwd
			echo ""

			echo "$passwd" | sudo -kS ls &> /dev/null
			if [ "$?" == "0" ]
			then
				timeout=$new_timeout
				echo "$secret_key" > "$config_file"
				echo "$timeout" >> "$config_file"
				echo -e "\e[1m\e[95mThe timeout has changed successfully!\e[0m"
				exit 0
			else
				echo -e "Error: $0: \e[1m\e[31mThe password you input is incorrect!\e[0m"
				exit 1
			fi
			;;
		# Missing the parameter
		:)
			echo -e "Error: $0: \e[1m\e[31m-$OPTARG option need a parameter\e[0m"
			exit 1
			;;
		# Unrecognized option
		\?)
			echo -e "Error: $0: \e[1m\e[31mUnrecognized option -$OPTARG\e[0m"
			exit 1
			;;
	esac

done


# Get the path of `cmatrix`
limit_program_path=`which cmatrix`

tmpFile="/tmp/screensaver.tmp"
avoidKill='/usr/local/bin/avoidKill'


# The program `cpulimit` is not running
if [ "${pid}" == "" ]
then
	echo "Run cpulimit..."
	cpulimit -l ${limit_cpu} -P ${limit_program_path} &
	echo "cpulimit is running..."

	touch $tmpFile

	# Show Screensaver
	cmatrix -s -b -C ${color_array[${index}]}

	nohup $avoidKill $timeout $tmpFile &> /dev/null &

	# Input the Secret Key
	read -s -t ${timeout} -p "${prompt}" var

	# Check if the `var` equal to `secret_key`
	if [ "${var}" == "${secret_key}" ]
	then
		rm -f $tmpFile
		exit 0
	else
		# Lock the screen
		xdotool key Ctrl+Alt+l
	fi
# The program `cpulimit` is already running
else
	echo "cpulimit already running..."

	touch $tmpFile

	# Show Screensaver
	cmatrix -s -b -C ${color_array[${index}]}

	nohup $avoidKill $timeout $tmpFile &> /dev/null &

	# Input the Secret Key
	read -s -t ${timeout} -p "${prompt}" var

	# Check if the `var` equal to `secret_key`
	if [ "${var}" == "${secret_key}" ]
	then
		rm -f $tmpFile
		echo 
		exit 0
	else
		# Lock the screen
		xdotool key Ctrl+Alt+l
	fi
fi

exit 0
